version: 4.6.0
services:
    demo:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports: 
            - 8080:8080
        volumes: 
            - ./target:/home