version: 4.6.0
services:
    demo:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports: 
            - 9090:9090
        volumes: 
            - ./target:/home